// Generated by gencpp from file centernet_ros/detecciones.msg
// DO NOT EDIT!


#ifndef CENTERNET_ROS_MESSAGE_DETECCIONES_H
#define CENTERNET_ROS_MESSAGE_DETECCIONES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <centernet_ros/deteccion.h>

namespace centernet_ros
{
template <class ContainerAllocator>
struct detecciones_
{
  typedef detecciones_<ContainerAllocator> Type;

  detecciones_()
    : header()
    , image_header()
    , data()  {
    }
  detecciones_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::centernet_ros::deteccion_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::centernet_ros::deteccion_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::centernet_ros::detecciones_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::centernet_ros::detecciones_<ContainerAllocator> const> ConstPtr;

}; // struct detecciones_

typedef ::centernet_ros::detecciones_<std::allocator<void> > detecciones;

typedef boost::shared_ptr< ::centernet_ros::detecciones > deteccionesPtr;
typedef boost::shared_ptr< ::centernet_ros::detecciones const> deteccionesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::centernet_ros::detecciones_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::centernet_ros::detecciones_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::centernet_ros::detecciones_<ContainerAllocator1> & lhs, const ::centernet_ros::detecciones_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_header == rhs.image_header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::centernet_ros::detecciones_<ContainerAllocator1> & lhs, const ::centernet_ros::detecciones_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace centernet_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::centernet_ros::detecciones_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::centernet_ros::detecciones_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centernet_ros::detecciones_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centernet_ros::detecciones_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centernet_ros::detecciones_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centernet_ros::detecciones_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::centernet_ros::detecciones_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4be5ca1bc1bc58da3c9b891aa8e7a4c";
  }

  static const char* value(const ::centernet_ros::detecciones_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4be5ca1bc1bc58dULL;
  static const uint64_t static_value2 = 0xa3c9b891aa8e7a4cULL;
};

template<class ContainerAllocator>
struct DataType< ::centernet_ros::detecciones_<ContainerAllocator> >
{
  static const char* value()
  {
    return "centernet_ros/detecciones";
  }

  static const char* value(const ::centernet_ros::detecciones_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::centernet_ros::detecciones_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Header image_header\n"
"deteccion[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: centernet_ros/deteccion\n"
"string Class\n"
"float64 probability\n"
"int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
"float64 depth\n"
"\n"
;
  }

  static const char* value(const ::centernet_ros::detecciones_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::centernet_ros::detecciones_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detecciones_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::centernet_ros::detecciones_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::centernet_ros::detecciones_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::centernet_ros::deteccion_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTERNET_ROS_MESSAGE_DETECCIONES_H
