// Generated by gencpp from file semantic_SLAM/DetectedObjects.msg
// DO NOT EDIT!


#ifndef SEMANTIC_SLAM_MESSAGE_DETECTEDOBJECTS_H
#define SEMANTIC_SLAM_MESSAGE_DETECTEDOBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <semantic_SLAM/ObjectInfo.h>

namespace semantic_SLAM
{
template <class ContainerAllocator>
struct DetectedObjects_
{
  typedef DetectedObjects_<ContainerAllocator> Type;

  DetectedObjects_()
    : header()
    , objects()  {
    }
  DetectedObjects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::semantic_SLAM::ObjectInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::semantic_SLAM::ObjectInfo_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObjects_

typedef ::semantic_SLAM::DetectedObjects_<std::allocator<void> > DetectedObjects;

typedef boost::shared_ptr< ::semantic_SLAM::DetectedObjects > DetectedObjectsPtr;
typedef boost::shared_ptr< ::semantic_SLAM::DetectedObjects const> DetectedObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::semantic_SLAM::DetectedObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::semantic_SLAM::DetectedObjects_<ContainerAllocator1> & lhs, const ::semantic_SLAM::DetectedObjects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::semantic_SLAM::DetectedObjects_<ContainerAllocator1> & lhs, const ::semantic_SLAM::DetectedObjects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace semantic_SLAM

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a74ced4691e2f209ce4fbe3dd6d24c31";
  }

  static const char* value(const ::semantic_SLAM::DetectedObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa74ced4691e2f209ULL;
  static const uint64_t static_value2 = 0xce4fbe3dd6d24c31ULL;
};

template<class ContainerAllocator>
struct DataType< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "semantic_SLAM/DetectedObjects";
  }

  static const char* value(const ::semantic_SLAM::DetectedObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ObjectInfo[] objects\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: semantic_SLAM/ObjectInfo\n"
"string type\n"
"float32 prob\n"
"int32 tl_x\n"
"int32 tl_y\n"
"int32 width\n"
"int32 height\n"
;
  }

  static const char* value(const ::semantic_SLAM::DetectedObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::semantic_SLAM::DetectedObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::semantic_SLAM::DetectedObjects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::semantic_SLAM::ObjectInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEMANTIC_SLAM_MESSAGE_DETECTEDOBJECTS_H
